### ISSUE TITLE
Feed broken after 9/20

### ISSUE THREAD

**Issue by jennyd20** [snarfed/plusstreamfeed#3]
My existing feed died after the Sept 20th check in, and my attempts to create a new feed are unsuccessful.  My feed reader claims that there's no feed found at the given URL(s).

**Comment by snarfed** [comment]
huh. sorry for the trouble! that's odd; i definitely see requests for your account for `/cookie?SID=DQAAAEg...` that succeed and serve successfully (ie return HTTP 200). i'm not sure why your feed reader is unhappy. is it still broken?

**Comment by jennyd20** [comment]
It started working again after a week or so of being broken - I should have closed down the issue when I noticed it, thanks for following up!
